### ISSUE TITLE
spark-mongo exited with code 0

### ISSUE THREAD

**Issue by mostafaghadimi** [JosemyD/docker-spark-mongo#4]
Hi @JosemyDuarte, whenever I run the docker-compose file which name is `spark-mongo.yml`, the   josemyd/docker-spark-mongo exited with code 0. It doesn't print anything else to follow the trace to find out what the problem is! 

Here is the screenshot I have taken:

![Screenshot from 2019-08-14 17-36-06](https://user-images.githubusercontent.com/24542893/63023483-75240480-beba-11e9-89b7-b429627ff3cb.png)

Also `docker-compose run spark-mongo`  works correctly and I connect to spark bash, but unfortunately `cd`, `ls` and other commands doesn't print anything or throw any error!

**Comment by JosemyDuarte** [comment]
Hi @mostafaghadimi! Yeah, `docker-compose run spark-mongo` is the way to go if you want to run `pyspark` directly, it's the default behavior. But is what you want is a shell, you can run `docker-compose run spark-mongo sh`. 

Take a look at this for more info: https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose

**Comment by mostafaghadimi** [comment]
@JosemyDuarte  is there any way to run `docker-compose -f spark-mongo.yml up` command without any problem?

**Comment by mostafaghadimi** [comment]
> Hi @mostafaghadimi! Yeah, `docker-compose run spark-mongo` is the way to go if you want to run `pyspark` directly, it's the default behavior. But is what you want is a shell, you can run `docker-compose run spark-mongo sh`.
> 
> Take a look at this for more info: https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose

how about docker-compose -f spark-mongo up?
It exits!

**Comment by JosemyDuarte** [comment]
> @JosemyDuarte is there any way to run `docker-compose -f spark-mongo.yml up` command without any problem?

It's hard. Because pyspark is an interactive shell. If you run it as you want you won't be able to write your commands because it will be run as a service, which means no interaction allowed.

What `docker-compose run spark-mongo` is doing is allowing you to interact with the command line. 

Sorry, but I can't think in a quick way to help you.

**Comment by mostafaghadimi** [comment]
@JosemyDuarte Unfortunately I still can't run the code properly.

```
>>> client.foo.bar.insert_many([{"x": 1.0, "y": -1.0}, {"x": 0.0, "y": 4.0}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 760, in insert_many
    blk.execute(write_concern, session=session)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/bulk.py", line 522, in execute
    return self.execute_command(generator, write_concern, session)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/bulk.py", line 345, in execute_command
    with client._tmp_session(session) as s:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1611, in _tmp_session
    s = self._ensure_session(session)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1598, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1551, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1584, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 429, in get_server_session
    None)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 200, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno -2] Name or service not known

```

**Comment by JosemyDuarte** [comment]
For me it's working man.. For what I can see in your logs you might not have mongo running.

![image](https://user-images.githubusercontent.com/6247860/63052741-69e3cf80-bee0-11e9-9146-4159f15b38d8.png)
